name: fitness_app
description: "This app "
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  
  # L10N
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  
  # HELPER
  equatable: ^2.0.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  get_it: ^7.6.6
  
  # FIREBASE
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter:
  assets:
    - assets/.env
    - assets/images/
  
  generate: true
  uses-material-design: true