name: fitness_app
description: "This app "
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  
  # L10N
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  
  # HELPER
  equatable: ^2.0.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  formz: ^0.6.1
  percent_indicator: 4.2.3
  syncfusion_flutter_charts: 24.1.46+1
  card_swiper: 3.0.1
  flutter_staggered_grid_view: 0.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  crypto: 3.0.3
  permission_handler: 11.2.0
  image_picker: 1.0.7
  bot_toast: 4.1.3
  youtube_player_flutter: 8.1.2

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  get_it: ^7.6.6
  
  # FIREBASE
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_app_check: 0.2.1+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/.env
    - assets/images/
    - assets/svgs/
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Regular.otf
    - family: Avenir-Bold
      fonts:
        - asset: assets/fonts/avenir/Avenir-Bold.otf

  generate: true
  uses-material-design: true